package club.anifox.android.presentation.common.ui.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFFfb923c)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDBC9)
val md_theme_light_onPrimaryContainer = Color(0xFF331200)
val md_theme_light_secondary = Color(0xFF96490C)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDBC8)
val md_theme_light_onSecondaryContainer = Color(0xFF321200)
val md_theme_light_tertiary = Color(0xFF855400)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDDB7)
val md_theme_light_onTertiaryContainer = Color(0xFF2A1700)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFFFEFB)
val light_onBackground = Color(0xFF0E121A)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF0E121A)
val md_theme_light_surfaceVariant = Color(0xFFFFFEFB)
val md_theme_light_onSurfaceVariant = Color(0xFFc4c4c4)
val md_theme_light_outline = Color(0xFF0E121A)
val md_theme_light_inverseOnSurface = Color(0xFFFBEEE9)
val md_theme_light_inverseSurface = Color(0xFF362F2C)
val md_theme_light_inversePrimary = Color(0xFFFFB68D)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF97480F)
val md_theme_light_outlineVariant = Color(0xFFD7C2B8)
val md_theme_light_scrim = Color(0xFFFFFFFF)

val dark_primary = Color(0xFFfb923c)
val md_theme_dark_onPrimary = Color(0xFF532200)
val md_theme_dark_primaryContainer = Color(0xFF763300)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDBC9)
val md_theme_dark_secondary = Color(0xFFFFB68B)
val md_theme_dark_onSecondary = Color(0xFF522300)
val md_theme_dark_secondaryContainer = Color(0xFF753400)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDBC8)
val md_theme_dark_tertiary = Color(0xFFFFB95D)
val md_theme_dark_onTertiary = Color(0xFF462A00)
val md_theme_dark_tertiaryContainer = Color(0xFF653E00)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDDB7)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF0E121A)
val dark_onBackground = Color(0xFFFFFEFB)
val md_theme_dark_surface = Color(0xFF201A17)
val md_theme_dark_onSurface = Color(0xFFFFFEFB)
val md_theme_dark_surfaceVariant = Color(0xFF0E121A)
val md_theme_dark_onSurfaceVariant = Color(0xFFc4c4c4)
val md_theme_dark_outline = Color(0xFFFFFEFB)
val md_theme_dark_inverseOnSurface = Color(0xFF201A17)
val md_theme_dark_inverseSurface = Color(0xFFECE0DB)
val md_theme_dark_inversePrimary = Color(0xFF97480F)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB68D)
val md_theme_dark_outlineVariant = Color(0xFFFFFEFB)
val md_theme_dark_scrim = Color(0xFF000000)




val darkGrey = Color(0xFF2B2B2B)
val lightGrey = Color(0xFF8F8F8F)
val purple = Color(0xFFC084FC)
val blueLight = Color(0xFF93C5FD)
val green = Color(0xFF34D399)
val orange = Color(0xFFFDBA74)



val seed = Color(0xFFFFBE9A)
